
- name: configure cron to run the ansible playbook every hour
  cron:
    name: configure aws hosts
    minute: "0"
    hour: "*" 
    job: "/usr/bin/ansible-playbook /home/centos/ansible/main.yaml -i /home/centos/ansible/aws.hosts"

- name: move files to azure jumphost every hour
  cron:
    name: move files to azure jumphost
    minute: "0"
    hour: "*"
    job: "scp -r /home/centos/ansible/ jumphost02.lot48labs.com:/home/centos/"