---
- name: Install Python 3.7 on CentOS 7
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Check if Python 3.7 is installed
      raw: /usr/local/bin/python3.7 --version
      register: python_version
      ignore_errors: true

    - name: Ensure EPEL repository is present
      raw: yum install -y epel-release
      when:
        - python_version.rc != 0

    - name: Install the necessary tools
      raw: yum install -y gcc openssl-devel bzip2-devel libffi-devel wget python3-dnf
      when:
        - python_version.rc != 0

    - name: Download Python 3.7 source code
      raw: |
        cd /usr/src
        wget https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz
      when:
        - python_version.rc != 0

    - name: Extract Python 3.7 source code
      raw: |
        cd /usr/src
        tar xzf Python-3.7.9.tgz
      when:
        - python_version.rc != 0

    - name: Compile and install Python 3.7
      raw: |
        cd /usr/src/Python-3.7.9
        ./configure --enable-optimizations
        make altinstall
      when:
        - python_version.rc != 0

    - name: Create a symlink for python3 if needed
      raw: ln -s /usr/local/bin/python3.7 /usr/bin/python3 || true
      when:
        - python_version.rc != 0

    - name: Ensure Python 3.7 is installed
      raw: /usr/local/bin/python3.7 --version
      when:
        - python_version.rc != 0