---
- hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yaml
  tasks:
    - name: Generate azure.hosts from template
      template:
        src: azure.hosts.j2
        dest: azure.hosts

    - name: Generate aws.hosts from template
      template:
        src: aws.hosts.j2
        dest: aws.hosts

    - name: Generate pce.hosts from template
      template:
        src: pce.hosts.j2
        dest: pce.hosts

    - name: Generate traffic.csv from template
      template:
        src: roles/linux/files/traffic.csv.j2
        dest: roles/linux/files/traffic.csv

  tags:
    - never
    - localhost


- name: Install Python 3.7 on CentOS 7
  hosts: pce
  gather_facts: no
  become: yes

  tasks:
    - name: Check if Python 3.7 is installed
      command: /usr/local/bin/python3.7 --version
      register: python_version
      ignore_errors: true

    - name: Ensure EPEL repository is present
      raw: yum install -y epel-release
      when:
        - python_version.rc != 0
        - centos_version == "7"

    - name: Install the necessary tools
      raw: yum install -y gcc openssl-devel bzip2-devel libffi-devel wget python3-dnf
      when:
        - python_version.rc != 0
        - centos_version == "7"

    - name: Download Python 3.7 source code
      raw: |
        cd /usr/src
        wget https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz
      when:
        - python_version.rc != 0
        - centos_version == "7"

    - name: Extract Python 3.7 source code
      raw: |
        cd /usr/src
        tar xzf Python-3.7.9.tgz
      when:
        - python_version.rc != 0
        - centos_version == "7"

    - name: Compile and install Python 3.7
      raw: |
        cd /usr/src/Python-3.7.9
        ./configure --enable-optimizations
        make altinstall
      when:
        - python_version.rc != 0
        - centos_version == "7"

    - name: Create a symlink for python3 if needed
      raw: ln -s /usr/local/bin/python3.7 /usr/bin/python3 || true
      when:
        - python_version.rc != 0
        - centos_version == "7"

    - name: Ensure Python 3.7 is installed
      raw: /usr/local/bin/python3.7 --version
      when:
        - python_version.rc != 0
        - centos_version == "7"

  tags:
    - never
    - centos7

- hosts: linux
  roles:
    - linux

- hosts: aws_jh_priv
  vars_files:
    - vars.yaml
  roles:
    - aws-jumphost

- hosts: aws_jh_pub
  vars_files:
    - vars.yaml
  roles:
    - aws-jumphost
  tasks:
    - name: Ensure /home/ubuntu/ansible directory exists
      ansible.builtin.file:
        path: /home/ubuntu/ansible
        state: directory
        mode: '0755'

    - name: Copy contents to /home/ubuntu/ansible on the remote host
      ansible.builtin.copy:
        src: ./  # Adjust this path to the directory you want to copy from, if necessary
        dest: /home/ubuntu/ansible
        remote_src: no
        directory_mode: '0755'
        force: yes
  tags:
    - never
    - aws_jh_pub

- hosts: azure_jh
  roles: 
    - azure-jumphost

- hosts: pce
  vars_files:
    - vars.yaml
  roles:
    - pce
  become: true
  tags:
    - never
    - pce