---
- name: Setup local hosts files
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yaml
  tags:
    - never
    - localhost
  tasks:
    - name: Generate azure.hosts from template
      template:
        src: azure.hosts.j2
        dest: azure.hosts

    - name: Generate aws.hosts from template
      template:
        src: aws.hosts.j2
        dest: aws.hosts

    - name: Generate pce.hosts from template
      template:
        src: pce.hosts.j2
        dest: pce.hosts

    - name: Generate traffic.csv from template
      template:
        src: roles/linux/files/traffic.csv.j2
        dest: roles/linux/files/traffic.csv

- name: Setup Linux hosts
  hosts: linux
  roles:
    - linux
- hosts: linux
  roles:
    - linux

- name: Setup AWS jumphost - private IP
  hosts: aws_jh_priv
  vars_files:
    - vars.yaml
  roles:
    - aws-jumphost

- name: Setup AWS jumphost - public IP
  hosts: aws_jh_pub
  vars_files:
    - vars.yaml
  tags:
    - never
    - aws_jh_pub
  roles:
    - aws-jumphost
  tasks:
    - name: Ensure /home/ubuntu/ansible directory exists
      ansible.builtin.file:
        path: /home/ubuntu/ansible
        state: directory
        mode: '0755'
    - name: Copy contents to /home/ubuntu/ansible on the remote host
      ansible.posix.synchronize:
        src: ./  # Adjust this path to the directory you want to copy from, if necessary
        dest: /home/ubuntu/ansible
        rsync_opts:
          - "--exclude=roles/pce/"
    - name: Copy SSH key to /home/ubuntu/.ssh on the remote host
      ansible.builtin.copy:
        src: ~/.ssh/{{ sshkey }}
        dest: /home/ubuntu/.ssh/{{ sshkey }}
        mode: '0600'
    - name: Install ansible on the remote host if not already installed
      ansible.builtin.shell: |
        if ! command -v ansible > /dev/null; then
          sudo apt update && sudo apt install ansible -y
        fi
      args:
        executable: /bin/bash

- name: Setup Azure jumphost
  hosts: azure_jh
  vars_files:
    - vars.yaml
  roles: 
    - azure-jumphost
  tasks:
    - name: Copy SSH key to /home/ubuntu/.ssh on the remote host
      ansible.builtin.copy:
        src: ~/.ssh/{{ sshkey }}
        dest: /home/ubuntu/.ssh/{{ sshkey }}
        mode: '0600'
    - name: Install ansible on the remote host if not already installed
      ansible.builtin.shell: |
        if ! command -v ansible > /dev/null; then
          sudo apt update && sudo apt install ansible -y
        fi
      args:
        executable: /bin/bash

- name: Setup PCE
  hosts: pce
  vars_files:
    - vars.yaml
  roles:
    - pce
  become: true
  tags:
    - never
    - pce