---
- name: Copy private ssh key
  ansible.builtin.copy:
    src: ~/.ssh/{{ sshkey }}
    dest: /home/{{ ansible_user }}/.ssh/{{ sshkey }}
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
- name: Copy ssh config file
  template:
    src: config.j2
    dest: /home/{{ ansible_user }}/.ssh/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'